export const MYSQL_DATA_TYPES = [
  'INT',
  'BIGINT',
  'SMALLINT',
  'TINYINT',
  'DECIMAL',
  'NUMERIC',
  'FLOAT',
  'DOUBLE',
  'BIT',
  'CHAR',
  'VARCHAR',
  'TEXT',
  'TINYTEXT',
  'MEDIUMTEXT',
  'LONGTEXT',
  'BINARY',
  'VARBINARY',
  'BLOB',
  'TINYBLOB',
  'MEDIUMBLOB',
  'LONGBLOB',
  'DATE',
  'TIME',
  'DATETIME',
  'TIMESTAMP',
  'YEAR',
  'BOOLEAN',
  'JSON',
  'ENUM',
  'SET',
  'GEOMETRY',
  'POINT',
  'LINESTRING',
  'POLYGON',
];

export function isRecognizedMysqlType(type: string): boolean {
  return MYSQL_DATA_TYPES.includes(type.trim().toUpperCase());
}
